name: precords_android
description: "PRecords – Football Players & Clubs Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"   # Dio 5.9+ requires Dart 3.4+

dependencies:
  flutter:
    sdk: flutter

  # Core
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  get: ^4.7.3
  flutter_dotenv: ^6.0.0
  get_storage: ^2.1.1

  # UI & Utilities
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2          # For picking player photo
  fluttertoast: ^8.2.8          # Beautiful toasts
  flutter_animate: ^4.5.0

  palette_generator: ^0.3.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
# name: precords_android
# description: "PRecords – Football Players & Clubs Management"
# publish_to: 'none'
# version: 1.0.0+1

# environment:
#   sdk: ">=3.10.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   # Core
#   dio: ^5.9.0
#   flutter_secure_storage: ^9.2.4
#   get: ^4.7.3
#   flutter_dotenv: ^6.0.0
#   get_storage: ^2.1.1            # ← ADDED: for saving dark mode preference

#   # UI & UX
#   cupertino_icons: ^1.0.8
#   cached_network_image: ^3.4.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^6.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - .env






